### PR TITLE
Extra args to database connection on MySQL

### LINKED ISSUE #40: Database port number
**Is your feature request related to a problem? Please describe.**
When i set my DB_URL, i also include the PORT like "localhost:1234". The problem is that the default port number ":3306" is always being concatenated ("localhost:1234:3306"), generating a connection error.

**Describe the solution you'd like**
There can be 2 solutions:

1. Check DB_URL and if a specified port is found, use it instead of the default.
2. Add an envirionment variable like DB_PORT to specify port to use.

**Describe alternatives you've considered**
No alternatives. Hard coded

**Additional context**
Port 3306 is the default one and works for most situations, yet, i can have more than one MySQL server running in different ports.

### PR DESCRIPTION
**Pull request by MatTerra**
Explain the **details** for making this change. What existing problem does the pull request solve?

The connection to the database only included basic arguments (host, user, password, database). Other arguments may be needed, as *port* and *ssl_ca*. This should be added in all levels, including the use_dao decorator to guarantee the possibility of personalizing the usage of such arguments without the need to change the DAO class code.

**Test plan (required)**

 - Added tests to MySQLPool to check the usage of database args on connect (There is no check if the available instance has this args set and this is the expected behavior, which is being tested)
 -  Added tests to MySQLHelper to check the usage
 - Added tests to GenericSQLDAO to check the usage
 - Added tests to use_dao to check usage of database_args

**Code formatting**
OK

**Closing issues**

closes #40

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the **CONTRIBUTING** document.
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by MatTerra** [comment]
@FabioTS, could you check if this solves your issue #40? I believe it should now be possible to include `port` in the database_args dict.

**Review by FabioTS — APPROVED** [review]
Well, it would do the trick for #40. I could set an environment variable and use it in `use_dao` decorator.
At the same time it allows flexibility for specifing a different database port for each function on my code. But, as i can see, it is limited to the host `DB_URL`.

**Comment by MatTerra** [comment]
Well, the decorator is really limited... I'll take a look at this.

**Comment by MatTerra** [comment]
@FabioTS, took your suggestion and changed the way we personalize the arguments to passed to dao in use_dao. Also added kwargs to dao, which are passed down to the MySQLHelper. I believe now we have the full flexibility

**Review by FabioTS — APPROVED** [review]

**Pull request merged**
